<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenLogViewer.Core\OpenLogViewer.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>olv-insights</AssemblyName>
    <RootNamespace>OpenLogViewer.Insights</RootNamespace>
  </PropertyGroup>

</Project>
